[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd buydrugs-next",
  "npm ci"
]

[phases.build]
cmds = [
  "cd buydrugs-next",
  "npm run build"
]

[start]
cmd = "cd buydrugs-next && npm run start"
